### ISSUE TITLE
Кнопки большие закрывают текст

### ISSUE THREAD

**Issue by Gvit0** [Gvit0/technomuseum#3]
![image](https://github.com/Gvit0/technomuseum/assets/90312305/15763f31-9208-4842-9d52-67649c5913f7)
уменьшить

**Comment by MaxiMax9055** [comment]
ок

**Comment by Gvit0** [comment]
![image](https://github.com/Gvit0/technomuseum/assets/90312305/8c75ca8a-0ec3-4926-b424-42b8de167ac5)
Текст не виден

**Comment by MaxiMax9055** [comment]
cthd gthtpfgecnb

**Comment by MaxiMax9055** [comment]
сервер перезапусти

**Comment by Gvit0** [comment]
это решено но кнопки маленькие текст не видно
