### ISSUE TITLE
Авторизация в техно музее почти готова...

### ISSUE THREAD

**Issue by MaxiMax9055** [Gvit0/technomuseum#4]
**но** для  продолжения установите _РНР5.4_ на сервер
кста для скачки по ссылке нужно после `href=" "`
нужно указать `download` и получается в итоге:
`<a href="адрес файла" download>текст ссыдки</a>`.

**Comment by MaxiMax9055** [comment]
Сделай поскорее

**Comment by Gvit0** [comment]
NO

**Comment by Gvit0** [comment]
Неправильный текст тем более это должен делать Олег

**Comment by MaxiMax9055** [comment]
Ок, авторизации не будет. РнР нуден для обработки форм на стороне сервера. Без этого момента запросы с стороны клиента (заполнение строк **логин** и **пароль**, ) и отправка на сервер с помощью кнопки “Войти“, он НЕ сможет обработать запрос, найти логин и пароль на сервере, проверить правильность и предоставить доступ к материалам аккаунта (при успешном заходе в личку). Вот для чего он на сервере нужен нужен

**Comment by Gvit0** [comment]
Она есть просто сохранять что зашло куда в куки не безопасно может любой подделать если по ip то нужно купить сертификат https если по маку то тоже купить надо

**Comment by MaxiMax9055** [comment]
> Она есть просто сохранять что зашло куда в куки не безопасно может любой подделать если по ip то нужно купить сертификат https если по маку то тоже купить надо

1. Кто "она"
2. "сохоронять что зашло" — У меня есть нормальный код с устранением этой проблемы
3. не сертификат https://, не MAC - адрес НЕ нужен.
Итог:
Гтово обсалютно всë, КРОМЕ PhP 5.4 на котором это должно работать.

**Comment by Gvit0** [comment]
> "сохоронять что зашло" — У меня есть нормальный код с устранением этой проблемы
У меня тоже есть сохронять что пользователь зашёл

**Comment by Gvit0** [comment]
![image](https://github.com/Gvit0/technomuseum/assets/90312305/4a9e2602-9351-445c-8dbd-9d7c1fc3503b)
хочешь покупай вот [ссылка](https://www.reg.ru/ssl-certificate/)

**Comment by Gvit0** [comment]
> Гтово обсалютно всë, КРОМЕ PhP 5.4 на котором это должно работать.
 НА ЭТОМ НЕДОЛЖНО РАБОТАТЬ ПРИМЕР https://pythonist.ru/10-izvestnyh-sajtov-sozdannyh-s-pomoshhyu-python/

**Comment by Gvit0** [comment]
> но для продолжения установите РНР5.4 на сервер
кста для скачки по ссылке нужно после href=" "
нужно указать download и получается в итоге:
<a href="адрес файла" download>текст ссыдки</a>.

ФАЙЛА НЕТУ РОЖКОВ ДОЛЖЕН СДЕЛАТЬ

**Comment by MaxiMax9055** [comment]
Если у тебя РЕАЛЬНО есть другой способ, окей без проблем, бери и делай

**Comment by Gvit0** [comment]
Это должен делать олег я должен делать только esp
